// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJmvqGEcu_-PjCJaxKIxidQg-swCq2eMU',
    appId: '1:286190165607:web:73c8e9ef9ba683c5577ec2',
    messagingSenderId: '286190165607',
    projectId: 'flash-chat-5cec7',
    authDomain: 'flash-chat-5cec7.firebaseapp.com',
    storageBucket: 'flash-chat-5cec7.appspot.com',
    measurementId: 'G-331Q4NK6Y2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJWvyFFCvMJ9GvOgu8HRPfYwFv4pymLCU',
    appId: '1:286190165607:android:795eddeb8c6db151577ec2',
    messagingSenderId: '286190165607',
    projectId: 'flash-chat-5cec7',
    storageBucket: 'flash-chat-5cec7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbrz4nsiQz8nr1mlwjZ84hb5wZJHyX-RY',
    appId: '1:286190165607:ios:515c0866abc39500577ec2',
    messagingSenderId: '286190165607',
    projectId: 'flash-chat-5cec7',
    storageBucket: 'flash-chat-5cec7.appspot.com',
    iosClientId: '286190165607-1frnjb9u35rksii7ls8ch6ndbhvqonnr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChattingApp',
  );
}
